url:
    canonical: example-site-multi-language
    extra: []

locale:
    default:
        key: cs
        name: cs_CZ
    extra: { en: en_US }

data:
    products: products.yml

form:
    contact:
        success_flash_message: Thank you for your message.
        handlers:
            -   type: email
                from:
                    name: MCS example-2 site
                    address: example-2@mcs.com
                recipients:
                    to: [ test.1@visionapps.cz ]
                    bcc: [ test.2@visionapps.cz ]
                templates:
                    subject: email/subject.html.twig
                    body: email/body.html.twig
            -   type: log
                file: form.log
        fields:
            name:
                - NotBlank: ~
            email:
                - NotBlank: ~
                - Email:
                    checkMX: true
            message:
                - NotBlank: ~

tracking:
    google_analytics: UA-example_ga_id

router:
    index:
        cs_CZ: /
        en_US: /
    product:
        cs_CZ: /zbozi/{product_slug | products:cs.slug}
        en_US: /products/{product_slug | products:en.slug}
    contact:
        cs_CZ: /kontakt
        en_US: /contact

renderer:
    index: index.html.twig
    product: product.html.twig
    contact: contact.html.twig
